spring:
  #关闭 thymeleaf 缓存
  thymeleaf:
    cache: false

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=UTF-8&ServerTimeZone=Asia/Shanghai
    username: root
    password: bill
    hikari:
      #连接池名
      pool-name: DataHikariCP
      #最小空闲连接数
      minimum-idle: 5
      #空闲连接存活最大时间 默认 10分钟（600000）
      idle-timeout: 1800000
      #最大连接数 默认 10
      maximum-pool-size: 10
      #从连接池返回的连接自动提交
      auto-commit: true
      #连接最大存活时间 0 表示永久存活，默认30分钟 （1800000）
      max-lifetime: 1800000
      #连接超时时间 默认 30 s
      connection-timeout: 30000
      #测试连接是否可用的查询语句
      connection-test-query: SELECT 1

  redis:
    host: 47.95.143.162
    port: 6379
    password: bill
    #超时时间
    timeout: 10000ms
    #连接池
    lettuce:
      pool:
        max-active: 8
        #最大连接阻塞等待时间 默认 -1
        max-wait: 10000ms
        #最大空闲连接
        max-idle: 200
        min-idle: 5


mybatis-plus:
  #配置 Mapper.xml 映射文件
  mapper-locations: classpath*:/mapper/*Mapper.xml
  #配置  MyBatis 数据返回类型别名 （默认别名是类名）
  type-aliases-package: com.bill.seckill.pojo

#MyBatis SQL 打印日志(方法接口所在的包，不是 Mapper.xml 所在的包)
logging:
  level:
    com.bill.seckill.mapper: debug
